while True:
   import random
 
   a=1
   b=50
   num = random.randint(a, b)

   example_list = ["a", "b", "c", "d","e", "f", "g","t", "x", "w", "v", "u", "y", "z", "A", "B", "C", "D","E", "F", "M", "N", "O", "P", "Q", "X", "Y", "Z", "1", "2", "3", "4","5", "6", "7", "8", "9", "0", "?", "!", "'", ";", ":", "@", "#", "$", "%", "^", "*", "&", "(", "{", "/", "}",]
   password=(example_list[random.randint(a, b)])
   password2=(example_list[random.randint(a, b)])
   password3=(example_list[random.randint(a, b)])
   password4=(example_list[random.randint(a, b)])
   password5=(example_list[random.randint(a, b)])
   password6=(example_list[random.randint(a, b)])
   password7=(example_list[random.randint(a, b)])
   password8=(example_list[random.randint(a, b)])
   password9=(example_list[random.randint(a, b)])
   password10=(example_list[random.randint(a, b)])
   password11=(example_list[random.randint(a, b)])
   password12=(example_list[random.randint(a, b)])
   password13=(example_list[random.randint(a, b)])
   password14=(example_list[random.randint(a, b)])
   password15=(example_list[random.randint(a, b)])
   print("Number 1:")
   print("  ")
   print(password + password2 + password3 + password4 + password5 + password6 + password7 + password8 + password9 + password10 + password11 + password12 + password13 + password14 + password15 + password8)
   print("  ")
   print("Number 2:")
   print("   ")
   password=(example_list[random.randint(a, b)])
   password2=(example_list[random.randint(a, b)])
   password3=(example_list[random.randint(a, b)])
   password4=(example_list[random.randint(a, b)])
   password5=(example_list[random.randint(a, b)])
   password6=(example_list[random.randint(a, b)])
   password7=(example_list[random.randint(a, b)])
   password8=(example_list[random.randint(a, b)])
   password9=(example_list[random.randint(a, b)])
   password10=(example_list[random.randint(a, b)])
   password11=(example_list[random.randint(a, b)])
   password12=(example_list[random.randint(a, b)])
   password13=(example_list[random.randint(a, b)])
   password14=(example_list[random.randint(a, b)])
   password15=(example_list[random.randint(a, b)])
   print(password + password2 + password3 + password4 + password5 + password6 + password7 + password8 + password9 + password10 + password11 + password12 + password13 + password14 + password15 + password8)
   print("  ")
   print("Number 3:")
   print(" ")
   password=(example_list[random.randint(a, b)])
   password2=(example_list[random.randint(a, b)])
   password3=(example_list[random.randint(a, b)])
   password4=(example_list[random.randint(a, b)])
   password5=(example_list[random.randint(a, b)])
   password6=(example_list[random.randint(a, b)])
   password7=(example_list[random.randint(a, b)])
   password8=(example_list[random.randint(a, b)])
   password9=(example_list[random.randint(a, b)])
   password10=(example_list[random.randint(a, b)])
   password11=(example_list[random.randint(a, b)])
   password12=(example_list[random.randint(a, b)])
   password13=(example_list[random.randint(a, b)])
   password14=(example_list[random.randint(a, b)])
   password15=(example_list[random.randint(a, b)])
   print(password + password2 + password3 + password4 + password5 + password6 + password7 + password8 + password9 + password10 + password11 + password12 + password13 + password14 + password15 + password8)
   
   break


